# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2017-02-21 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0002_auto_20170221_1851'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'verbose_name': '版块', 'verbose_name_plural': '版块（列表）'},
        ),
        migrations.AddField(
            model_name='block',
            name='status',
            field=models.IntegerField(choices=[(0, '正常'), (-1, '删除')], default=0, verbose_name='状态'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='block',
            name='admin',
            field=models.CharField(max_length=100, verbose_name='版块管理员名称'),
        ),
        migrations.AlterField(
            model_name='block',
            name='descp',
            field=models.CharField(max_length=100, verbose_name='版块描述'),
        ),
        migrations.AlterField(
            model_name='block',
            name='name',
            field=models.CharField(max_length=100, verbose_name='版块名称'),
        ),
    ]
