# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2017-02-22 05:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('block', '0003_auto_20170221_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='版块名称')),
                ('content', models.CharField(max_length=10000, verbose_name='版块内容')),
                ('status', models.IntegerField(choices=[(0, '正常'), (-1, '删除')], verbose_name='状态')),
                ('create_timestamp', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('last_update_timestamp', models.DateField(auto_now=True, verbose_name='最后更新时刻')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='block.Block', verbose_name='版块ID')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章（列表）',
            },
        ),
    ]
