# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2017-02-22 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(default=0, max_length=100, verbose_name='Freddy'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='block.Block', verbose_name='文章ID'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.CharField(max_length=10000, verbose_name='文章内容'),
        ),
        migrations.AlterField(
            model_name='article',
            name='create_timestamp',
            field=models.DateField(auto_now_add=True, verbose_name='文章创建时间'),
        ),
        migrations.AlterField(
            model_name='article',
            name='last_update_timestamp',
            field=models.DateField(auto_now=True, verbose_name='文章更新时刻'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=100, verbose_name='文章名称'),
        ),
    ]
