# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2017-02-28 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20170227_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='文章创建时间'),
        ),
    ]
